// Generated from Clash_Merge.yaml by scripts/generate_clash_script.rb.
// Paste this entire file into Clash Verge's "Global Extend Script" editor.
// It preserves subscription-defined groups and non-terminal rules.
// Do not edit this file manually.

var CUSTOM_PROXY_GROUPS = [
  {
    "name": "🇭🇰 香港节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇭🇰|HK|Hong|香港|深港|沪港|京港|港"
  },
  {
    "name": "🇹🇼 台湾节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇹🇼|TW|TWN|Taiwan|Taipei|台湾|台灣|台北|台中|新北|彰化"
  },
  {
    "name": "🇯🇵 日本节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇯🇵|JP|Japan|Tokyo|日本|东京|大阪"
  },
  {
    "name": "🇸🇬 新加坡节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇸🇬|SG|Singapore|新加坡|狮城|新国"
  },
  {
    "name": "🇺🇸 美国节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇺🇸|US|USA|America|United States|美国|凤凰城|洛杉矶|西雅图|芝加哥|纽约|沪美|美"
  },
  {
    "name": "🇰🇷 韩国节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇰🇷|KR|KOR|Korea|韩国|韓國|首尔|首爾|釜山"
  },
  {
    "name": "🇻🇳 越南节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇻🇳|VN|VNM|Vietnam|越南|河内|河內|胡志明"
  },
  {
    "name": "🇲🇾 马来西亚节点",
    "type": "select",
    "include-all": true,
    "filter": "(?i)🇲🇾|MY|MYS|Malaysia|马来西亚|馬來西亞|吉隆坡"
  },
  {
    "name": "🌐 其他节点",
    "type": "select",
    "include-all": true,
    "exclude-filter": "(?i)🇭🇰|HK|Hong|香港|深港|沪港|京港|港|🇹🇼|TW|TWN|Taiwan|Taipei|台湾|台灣|台北|台中|新北|彰化|🇯🇵|JP|Japan|Tokyo|日本|东京|大阪|🇸🇬|SG|Singapore|新加坡|狮城|新国|🇺🇸|US|USA|America|United States|美国|凤凰城|洛杉矶|西雅图|芝加哥|纽约|沪美|美|🇰🇷|KR|KOR|Korea|韩国|韓國|首尔|首爾|釜山|🇻🇳|VN|VNM|Vietnam|越南|河内|河內|胡志明|🇲🇾|MY|MYS|Malaysia|马来西亚|馬來西亞|吉隆坡"
  },
  {
    "name": "🚀 节点选择",
    "type": "select",
    "include-all": true,
    "proxies": [
      "🇰🇷 韩国节点",
      "DIRECT",
      "REJECT",
      "🇭🇰 香港节点",
      "🇹🇼 台湾节点",
      "🇯🇵 日本节点",
      "🇸🇬 新加坡节点",
      "🇺🇸 美国节点",
      "🇻🇳 越南节点",
      "🇲🇾 马来西亚节点",
      "🌐 其他节点"
    ],
    "default-selected": "🇰🇷 韩国节点"
  },
  {
    "name": "🧱 DNS 防泄露",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "REJECT",
      "DIRECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "🤖 AI 服务",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "🇺🇸 美国节点",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "📺 MissAV",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "🇺🇸 美国节点",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "📹 油管视频",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "🔍 谷歌服务",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "🇯🇵 日本节点",
      "🇭🇰 香港节点",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "Ⓜ️ 微软服务",
    "type": "select",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "REJECT"
    ],
    "default-selected": "DIRECT"
  },
  {
    "name": "🍏 苹果服务",
    "type": "select",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "REJECT"
    ],
    "default-selected": "DIRECT"
  },
  {
    "name": "🍎 苹果推送",
    "type": "select",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "REJECT"
    ],
    "default-selected": "DIRECT"
  },
  {
    "name": "📲 电报消息",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "🐱 代码托管",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "🏦 汇丰香港",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "🇭🇰 香港节点",
      "DIRECT",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "🏦 香港银行",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "🇭🇰 香港节点",
      "REJECT"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "📈 券商服务",
    "type": "select",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🇭🇰 香港节点",
      "REJECT"
    ],
    "default-selected": "DIRECT"
  },
  {
    "name": "🏠 私有网络",
    "type": "select",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "REJECT"
    ],
    "default-selected": "DIRECT"
  },
  {
    "name": "🔒 国内服务",
    "type": "select",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "REJECT"
    ],
    "default-selected": "DIRECT"
  },
  {
    "name": "🌍 非中国",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "REJECT",
      "🇯🇵 日本节点"
    ],
    "default-selected": "🚀 节点选择"
  },
  {
    "name": "🐟 漏网之鱼",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "REJECT",
      "🇯🇵 日本节点"
    ],
    "default-selected": "🚀 节点选择"
  }
];
var CUSTOM_RULE_PROVIDERS = {
  "youngtree-missav": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-missav.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/MissAV.yaml"
  },
  "youngtree-google": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-google.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/Google.yaml"
  },
  "youngtree-ai": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-ai.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/AI.yaml"
  },
  "youngtree-hsbc-hk": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-hsbc-hk.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/HSBC_HK.yaml"
  },
  "youngtree-hk-banks-direct": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-hk-banks-direct.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/HK_Banks_Direct.yaml"
  },
  "youngtree-hk-broker": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-hk-broker.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/HK_Broker.yaml"
  },
  "youngtree-apple-push": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-apple-push.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/ApplePush.yaml"
  },
  "youngtree-apple": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/youngtree-apple.yaml",
    "url": "https://raw.githubusercontent.com/youngtreebig-droid/Shadowrocket-Rules/refs/heads/main/Clash/rules/Apple.yaml"
  },
  "blackmatrix-block-http-dns": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-block-http-dns.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.yaml"
  },
  "blackmatrix-youtube": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-youtube.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
  },
  "blackmatrix-bilibili": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-bilibili.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
  },
  "blackmatrix-lan": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-lan.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
  },
  "blackmatrix-telegram": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-telegram.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
  },
  "blackmatrix-github": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-github.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml"
  },
  "blackmatrix-gitlab": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-gitlab.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitLab/GitLab.yaml"
  },
  "blackmatrix-atlassian": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-atlassian.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Atlassian/Atlassian.yaml"
  },
  "blackmatrix-microsoft": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-microsoft.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
  },
  "blackmatrix-china": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-china.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml"
  },
  "blackmatrix-xiaohongshu": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-xiaohongshu.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoHongShu/XiaoHongShu.yaml"
  },
  "loyalsoldier-direct": {
    "type": "http",
    "behavior": "domain",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/loyalsoldier-direct.yaml",
    "url": "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
  },
  "blackmatrix-global": {
    "type": "http",
    "behavior": "classical",
    "format": "yaml",
    "interval": 86400,
    "proxy": "🚀 节点选择",
    "path": "./ruleset/blackmatrix-global.yaml",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml"
  }
};
var PREPEND_RULES = [
  "DOMAIN,localhost.weixin.qq.com,DIRECT",
  "DOMAIN-SUFFIX,local,🏠 私有网络",
  "DOMAIN-SUFFIX,in-addr.arpa,🏠 私有网络",
  "DOMAIN-SUFFIX,ip6.arpa,🏠 私有网络",
  "DOMAIN,shortconn.im.qcloud.com,🔒 国内服务",
  "DOMAIN-SUFFIX,doubao.com,🔒 国内服务",
  "AND,((NETWORK,TCP),(DST-PORT,5223)),🍎 苹果推送",
  "RULE-SET,youngtree-missav,📺 MissAV",
  "DOMAIN-KEYWORD,missav,📺 MissAV",
  "IP-CIDR,208.54.0.0/16,🇺🇸 美国节点,no-resolve",
  "RULE-SET,blackmatrix-block-http-dns,🧱 DNS 防泄露",
  "DOMAIN,translate.googleapis.com,📹 油管视频",
  "DOMAIN,translate-pa.googleapis.com,📹 油管视频",
  "RULE-SET,youngtree-google,🔍 谷歌服务",
  "RULE-SET,youngtree-ai,🤖 AI 服务",
  "RULE-SET,blackmatrix-youtube,📹 油管视频",
  "RULE-SET,blackmatrix-bilibili,🔒 国内服务",
  "RULE-SET,blackmatrix-lan,🏠 私有网络",
  "RULE-SET,blackmatrix-telegram,📲 电报消息",
  "RULE-SET,blackmatrix-github,🐱 代码托管",
  "RULE-SET,blackmatrix-gitlab,🐱 代码托管",
  "RULE-SET,blackmatrix-atlassian,🐱 代码托管",
  "RULE-SET,blackmatrix-microsoft,Ⓜ️ 微软服务",
  "RULE-SET,youngtree-hsbc-hk,🏦 汇丰香港",
  "RULE-SET,youngtree-hk-banks-direct,🏦 香港银行",
  "RULE-SET,youngtree-hk-broker,📈 券商服务",
  "RULE-SET,youngtree-apple-push,🍎 苹果推送",
  "RULE-SET,youngtree-apple,🍏 苹果服务",
  "RULE-SET,blackmatrix-xiaohongshu,🔒 国内服务",
  "RULE-SET,loyalsoldier-direct,🔒 国内服务",
  "RULE-SET,blackmatrix-china,🔒 国内服务"
];
var DEFERRED_RULES = [
  "GEOIP,CN,🔒 国内服务",
  "RULE-SET,blackmatrix-global,🌍 非中国",
  "MATCH,🐟 漏网之鱼"
];

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function hasOwn(object, key) {
  return Object.prototype.hasOwnProperty.call(object, key);
}

function copyOwnProperties(target, source) {
  for (var key in source) {
    if (hasOwn(source, key)) {
      target[key] = source[key];
    }
  }
  return target;
}

function buildNameLookup(groups) {
  var names = {};
  groups.forEach(function (group) {
    names[group.name] = true;
  });
  return names;
}

function buildRuleLookup(rules) {
  var lookup = {};
  rules.forEach(function (rule) {
    lookup[rule] = true;
  });
  return lookup;
}

function isTerminalRule(rule) {
  return typeof rule === "string" &&
    (rule.indexOf("MATCH,") === 0 || rule.indexOf("FINAL,") === 0);
}

function main(config, _profileName) {
  if (!isObject(config)) {
    throw new Error("The subscription configuration must be an object.");
  }

  var customGroupNames = buildNameLookup(CUSTOM_PROXY_GROUPS);
  var existingGroups = Array.isArray(config["proxy-groups"]) ? config["proxy-groups"] : [];
  var preservedGroups = existingGroups.filter(function (group) {
    return !isObject(group) || typeof group.name !== "string" || !hasOwn(customGroupNames, group.name);
  });
  config["proxy-groups"] = preservedGroups.concat(CUSTOM_PROXY_GROUPS);

  var existingProviders = isObject(config["rule-providers"]) ? config["rule-providers"] : {};
  config["rule-providers"] = copyOwnProperties(
    copyOwnProperties({}, existingProviders),
    CUSTOM_RULE_PROVIDERS
  );

  var customRules = buildRuleLookup(PREPEND_RULES.concat(DEFERRED_RULES));
  var existingRules = Array.isArray(config.rules) ? config.rules : [];
  var preservedRules = existingRules.filter(function (rule) {
    return typeof rule === "string" && !hasOwn(customRules, rule) && !isTerminalRule(rule);
  });
  config.rules = PREPEND_RULES.concat(preservedRules, DEFERRED_RULES);

  var profile = isObject(config.profile) ? config.profile : {};
  profile["store-selected"] = true;
  config.profile = profile;
  return config;
}
