#!/usr/bin/env python3
"""Generate Mihomo classical rule providers from the repository's .list files."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = ROOT / "Clash" / "rules"
SOURCE_FILES = (
    ("MissAV.list", "MissAV.yaml"),
    ("AI.list", "AI.yaml"),
    ("Apple.list", "Apple.yaml"),
    ("ApplePush.list", "ApplePush.yaml"),
    ("Google.list", "Google.yaml"),
    ("HSBC_HK.list", "HSBC_HK.yaml"),
    ("HK_Banks_Direct.list", "HK_Banks_Direct.yaml"),
    ("HK_Broker.list", "HK_Broker.yaml"),
)

# These Shadowrocket rule types have no Mihomo equivalent.
OMITTED_RULE_TYPES = {"URL-REGEX", "USER-AGENT"}
SUPPORTED_RULE_TYPES = {
    "AND",
    "DOMAIN",
    "DOMAIN-KEYWORD",
    "DOMAIN-REGEX",
    "DOMAIN-SUFFIX",
    "DOMAIN-WILDCARD",
    "DSCP",
    "DST-PORT",
    "GEOIP",
    "GEOSITE",
    "IN-NAME",
    "IN-PORT",
    "IN-TYPE",
    "IN-USER",
    "IP-ASN",
    "IP-CIDR",
    "IP-CIDR6",
    "IP-SUFFIX",
    "NETWORK",
    "NOT",
    "OR",
    "PROCESS-NAME",
    "PROCESS-NAME-REGEX",
    "PROCESS-NAME-WILDCARD",
    "PROCESS-PATH",
    "PROCESS-PATH-REGEX",
    "PROCESS-PATH-WILDCARD",
    "REMATCH-NAME",
    "SRC-GEOIP",
    "SRC-IP-ASN",
    "SRC-IP-CIDR",
    "SRC-IP-SUFFIX",
    "SRC-PORT",
    "UID",
}


class ConversionError(ValueError):
    """Raised when a source list has a rule that cannot be converted safely."""


def parse_source(source: Path) -> tuple[list[str], Counter[str]]:
    rules: list[str] = []
    omitted: Counter[str] = Counter()

    for line_number, raw_line in enumerate(source.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        rule_type = line.partition(",")[0]
        if rule_type in OMITTED_RULE_TYPES:
            omitted[rule_type] += 1
            continue
        if rule_type not in SUPPORTED_RULE_TYPES:
            raise ConversionError(
                f"{source.relative_to(ROOT)}:{line_number}: unsupported rule type "
                f"{rule_type!r}; update the converter before publishing it to Mihomo."
            )
        if "," not in line:
            raise ConversionError(
                f"{source.relative_to(ROOT)}:{line_number}: malformed rule {line!r}."
            )
        rules.append(line)

    return rules, omitted


def render(source: Path, rules: list[str], omitted: Counter[str]) -> str:
    omitted_description = (
        ", ".join(f"{rule_type} ({count})" for rule_type, count in sorted(omitted.items()))
        if omitted
        else "none"
    )
    lines = [
        f"# Generated from {source.name} by scripts/generate_clash_rule_providers.py.",
        "# Do not edit this file manually; edit the source list and regenerate it instead.",
        f"# Shadowrocket-only rules intentionally omitted: {omitted_description}.",
        "payload:",
    ]
    lines.extend(f"  - {json.dumps(rule, ensure_ascii=False)}" for rule in rules)
    return "\n".join(lines) + "\n"


def generate(check: bool) -> int:
    expected: dict[Path, str] = {}
    for source_name, output_name in SOURCE_FILES:
        source = ROOT / source_name
        rules, omitted = parse_source(source)
        output = OUTPUT_DIRECTORY / output_name
        expected[output] = render(source, rules, omitted)
        print(
            f"{source.name} -> {output.relative_to(ROOT)}: "
            f"{len(rules)} rules, omitted {sum(omitted.values())}"
        )

    stale_outputs = [
        output
        for output, content in expected.items()
        if not output.exists() or output.read_text(encoding="utf-8") != content
    ]
    if check:
        if stale_outputs:
            for output in stale_outputs:
                print(
                    f"{output.relative_to(ROOT)} is out of date; "
                    "run scripts/generate_clash_rule_providers.py.",
                    file=sys.stderr,
                )
            return 1
        return 0

    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for output in stale_outputs:
        output.write_text(expected[output], encoding="utf-8")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Clash/Mihomo rule providers from the local .list files."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated providers are not current",
    )
    args = parser.parse_args()
    try:
        return generate(args.check)
    except (ConversionError, OSError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
