#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "yaml"

ROOT = File.expand_path("..", __dir__)
MERGE_CONFIG = File.join(ROOT, "Clash_Merge.yaml")
SCRIPT_OUTPUT = File.join(ROOT, "Clash_Script.js")
DEFERRED_RULES = [
  "GEOIP,CN,🔒 国内服务",
  "RULE-SET,blackmatrix-global,🌍 非中国",
  "MATCH,🐟 漏网之鱼"
].freeze

def read_merge_config
  config = YAML.load_file(MERGE_CONFIG)
  %w[proxy-groups rule-providers rules].each do |key|
    raise "#{MERGE_CONFIG} is missing #{key}" unless config.key?(key)
  end
  raise "#{MERGE_CONFIG} proxy-groups must be an array" unless config["proxy-groups"].is_a?(Array)
  raise "#{MERGE_CONFIG} rule-providers must be an object" unless config["rule-providers"].is_a?(Hash)
  raise "#{MERGE_CONFIG} rules must be an array" unless config["rules"].is_a?(Array)
  raise "#{MERGE_CONFIG} is missing deferred rules" unless (DEFERRED_RULES - config["rules"]).empty?

  config
end

def render_script(config)
  prepend_rules = config["rules"].reject { |rule| DEFERRED_RULES.include?(rule) }
  groups = JSON.pretty_generate(config["proxy-groups"], ascii_only: false)
  providers = JSON.pretty_generate(config["rule-providers"], ascii_only: false)
  prepend = JSON.pretty_generate(prepend_rules, ascii_only: false)
  deferred = JSON.pretty_generate(DEFERRED_RULES, ascii_only: false)

  <<~JAVASCRIPT
    // Generated from Clash_Merge.yaml by scripts/generate_clash_script.rb.
    // Paste this entire file into Clash Verge's "Global Extend Script" editor.
    // It preserves subscription-defined groups and non-terminal rules.
    // Do not edit this file manually.

    var CUSTOM_PROXY_GROUPS = #{groups};
    var CUSTOM_RULE_PROVIDERS = #{providers};
    var PREPEND_RULES = #{prepend};
    var DEFERRED_RULES = #{deferred};

    function isObject(value) {
      return value !== null && typeof value === "object" && !Array.isArray(value);
    }

    function hasOwn(object, key) {
      return Object.prototype.hasOwnProperty.call(object, key);
    }

    function copyOwnProperties(target, source) {
      for (var key in source) {
        if (hasOwn(source, key)) {
          target[key] = source[key];
        }
      }
      return target;
    }

    function buildNameLookup(groups) {
      var names = {};
      groups.forEach(function (group) {
        names[group.name] = true;
      });
      return names;
    }

    function buildRuleLookup(rules) {
      var lookup = {};
      rules.forEach(function (rule) {
        lookup[rule] = true;
      });
      return lookup;
    }

    function isTerminalRule(rule) {
      return typeof rule === "string" &&
        (rule.indexOf("MATCH,") === 0 || rule.indexOf("FINAL,") === 0);
    }

    function main(config, _profileName) {
      if (!isObject(config)) {
        throw new Error("The subscription configuration must be an object.");
      }

      var customGroupNames = buildNameLookup(CUSTOM_PROXY_GROUPS);
      var existingGroups = Array.isArray(config["proxy-groups"]) ? config["proxy-groups"] : [];
      var preservedGroups = existingGroups.filter(function (group) {
        return !isObject(group) || typeof group.name !== "string" || !hasOwn(customGroupNames, group.name);
      });
      config["proxy-groups"] = preservedGroups.concat(CUSTOM_PROXY_GROUPS);

      var existingProviders = isObject(config["rule-providers"]) ? config["rule-providers"] : {};
      config["rule-providers"] = copyOwnProperties(
        copyOwnProperties({}, existingProviders),
        CUSTOM_RULE_PROVIDERS
      );

      var customRules = buildRuleLookup(PREPEND_RULES.concat(DEFERRED_RULES));
      var existingRules = Array.isArray(config.rules) ? config.rules : [];
      var preservedRules = existingRules.filter(function (rule) {
        return typeof rule === "string" && !hasOwn(customRules, rule) && !isTerminalRule(rule);
      });
      config.rules = PREPEND_RULES.concat(preservedRules, DEFERRED_RULES);

      var profile = isObject(config.profile) ? config.profile : {};
      profile["store-selected"] = true;
      config.profile = profile;
      return config;
    }
  JAVASCRIPT
end

config = read_merge_config
expected = render_script(config)

if ARGV == ["--check"]
  abort "#{SCRIPT_OUTPUT} is out of date; run scripts/generate_clash_script.rb." unless File.exist?(SCRIPT_OUTPUT) && File.read(SCRIPT_OUTPUT) == expected
elsif ARGV.empty?
  File.write(SCRIPT_OUTPUT, expected)
else
  abort "Usage: #{$PROGRAM_NAME} [--check]"
end
